name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cp docker-compose.yml.dist docker-compose.yml
        cp ./backend/.env.template ./backend/.env
        docker-compose up --build -d
        docker exec fastapi-cleanings-server pytest -v
